import { normalizeTeamName } from './helper';

const fifaTeamCodeByNormalizedName = new Map<string, string>([
	['tjeckien', 'CZE'],
	['mexiko', 'MEX'],
	['sydafrika', 'RSA'],
	['sydkorea', 'KOR'],
	['bosnien och hercegovina', 'BIH'],
	['kanada', 'CAN'],
	['qatar', 'QAT'],
	['schweiz', 'SUI'],
	['brasilien', 'BRA'],
	['haiti', 'HAI'],
	['marocko', 'MAR'],
	['skottland', 'SCO'],
	['australien', 'AUS'],
	['paraguay', 'PAR'],
	['turkiet', 'TUR'],
	['usa', 'USA'],
	['curaçao', 'CUW'],
	['curacao', 'CUW'],
	['ecuador', 'ECU'],
	['tyskland', 'GER'],
	['elfenbenskusten', 'CIV'],
	['japan', 'JPN'],
	['nederlanderna', 'NED'],
	['nederländerna', 'NED'],
	['sverige', 'SWE'],
	['tunisien', 'TUN'],
	['belgien', 'BEL'],
	['egypten', 'EGY'],
	['iran', 'IRN'],
	['nya zeeland', 'NZL'],
	['kap verde', 'CPV'],
	['saudiarabien', 'KSA'],
	['spanien', 'ESP'],
	['uruguay', 'URU'],
	['frankrike', 'FRA'],
	['irak', 'IRQ'],
	['norge', 'NOR'],
	['senegal', 'SEN'],
	['algeriet', 'ALG'],
	['argentina', 'ARG'],
	['osterrike', 'AUT'],
	['österrike', 'AUT'],
	['jordanien', 'JOR'],
	['colombia', 'COL'],
	['demokratiska republiken kongo', 'COD'],
	['portugal', 'POR'],
	['uzbekistan', 'UZB'],
	['kroatien', 'CRO'],
	['england', 'ENG'],
	['ghana', 'GHA'],
	['panama', 'PAN'],
]);

export const getFifaTeamCode = (teamName: string) =>
	fifaTeamCodeByNormalizedName.get(normalizeTeamName(teamName));
